### PR TITLE
Adds get_tips method

### PR DESCRIPTION
**Pull request by stevenweaver**

### CODE REVIEW

**Comment by spond** [comment]
I can port to d3.v5 when this pull request has been merged. You can then create an ES6 module?

**Comment by stevenweaver** [comment]
@spond - Yes. I'm going to publish 0.2.0-alpha to npm shortly after I merge this change, which is necessary for the notebooks I've created to work. I'll share what I have at that point. 

Ok. Our current problem is outlined succinctly by Tom MacWright under Requiring stubborn add-ons [here](https://beta.observablehq.com/@tmcw/requiring-modules-troubleshooting).

I'm unsure that d3v5 will fix the problem in whole, but it will certainly help. I've also found myself have to mix d3v5 and d3v3 together in the same notebooks due to Observable being designed around the use of Promises in each cell.

**Comment by spond** [comment]
d3v5 won't fix inclusion issues by itself, since we are essentially injecting variables into the `d3` global. I would imagine the preferred solution is to break phylotree into its own namespace/module, which will break current usage examples, but may be inevitable

**Comment by stevenweaver** [comment]
@spond - This is the current collection of Observables. https://beta.observablehq.com/collection/@stevenweaver/phylotree-utilities. 

I will start fleshing them out with short blurbs. I did not see a "group collections" feature immediately, so the collection is currently under my username.

**Pull request merged**
