### PR TITLE
Parse tagged newick strings

### PR DESCRIPTION
**Pull request by stephenshank**
Tags no longer show up in node names. They are now added to node elements as a key with value true, similar to how branch selection on the main application works. Main application can parse and visualize trees with a single tag called "Foreground".

### CODE REVIEW

**Comment by stephenshank** [comment]
See the following movie, which was created with this newick string:

`(((EELA:0.150276,CONGERA:0.213019):0.230956,(EELB:0.263487,CONGERB:0.202633):0.246917):0.094785,((CAVEFISH{Foreground}:0.451027,(GOLDFISH{Foreground}:0.340495,ZEBRAFISH{Foreground}:0.390163){Foreground}:0.220565):0.067778,((((((NSAM:0.008113,NARG:0.014065):0.052991,SPUN:0.061003,(SMIC:0.027806,SDIA:0.015298,SXAN:0.046873):0.046977):0.009822,(NAUR:0.081298,(SSPI:0.023876,STIE:0.013652):0.058179):0.091775):0.073346,(MVIO:0.012271,MBER:0.039798):0.178835):0.147992,((BFNKILLIFISH:0.317455,(ONIL:0.029217,XCAU:0.084388):0.201166):0.055908,THORNYHEAD:0.252481):0.061905):0.157214,LAMPFISH:0.717196,((SCABBARDA:0.189684,SCABBARDB:0.362015):0.282263,((VIPERFISH:0.318217,BLACKDRAGON:0.109912):0.123642,LOOSEJAW:0.3971):0.287152):0.140663):0.206729):0.222485,(COELACANTH{Foreground}:0.558103,((CLAWEDFROG{Foreground}:0.441842,SALAMANDER{Foreground}:0.299607){Foreground}:0.135307,((CHAMELEON{Foreground}:0.771665,((PIGEON{Foreground}:0.150909,CHICKEN{Foreground}:0.172733){Foreground}:0.082163,ZEBRAFINCH{Foreground}:0.099172){Foreground}:0.272338){Foreground}:0.014055,((BOVINE{Foreground}:0.167569,DOLPHIN{Foreground}:0.15745){Foreground}:0.104783,ELEPHANT{Foreground}:0.166557){Foreground}:0.367205){Foreground}:0.050892){Foreground}:0.114731):0.295021)`

parse_tags

**Comment by stephenshank** [comment]
@stevenweaver The main viewer now handles multiple annotations. The following files should be useful for verification. 
[single-tag.txt](https://github.com/veg/phylotree.js/files/1482908/single-tag.txt)
[two_tags.txt](https://github.com/veg/phylotree.js/files/1482909/two_tags.txt)
[three-tags.txt](https://github.com/veg/phylotree.js/files/1482910/three-tags.txt)

**Comment by stevenweaver** [comment]
Hi Stephen, 
It looks like this commit causes phylotree to fail when it previously wasn't. The tree successfully parses with ETE toolkit and throws an exception at line 860.

[broken.txt](https://github.com/veg/phylotree.js/files/1497205/broken.txt)

Best,

**Comment by stephenshank** [comment]
Hello @stevenweaver ,
I am having a hard time reproducing the error... when I check out [the last commit](https://github.com/veg/phylotree.js/pull/47/commits/60212346cdb094353817d9f166f83a9c1cdb9fcf) and try to load your tree in the main application, my experience seems as it should... please see the attached image. Can you provide more information on exactly how your failure occurs?

Thanks,
broken

**Pull request merged**
